This project contains numerous mojos that can be used in your eclipse-repository (or other) builds.

== Currently used mojos

:frame: all
:grid: all
:halign: left
:valign: top

[cols="3a,3a,10a,3a", options="header"]
|===
|Mojo
|Goal
|Description
|Example

| ###### *CompareWithBaselineMojo*
|
compare-version-with-baselines
|
Checks that the artifactrs being built are correctrly versioned relative a previously released update site baseline
|
link:https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L412-L430[Example pom]

| ###### *GenerateCompositeSite*
|
generate-composite-site
|
Headless mojo that can generate a composite site from one or more folders, URLs, or paths; can also generate a composite site by reading a remote index page and searching for child folders, similar to https://github.com/jbosstools/jbosstools-build-ci/blob/jbosstools-4.4.x/util/cleanup/jbosstools-cleanup.sh#L255
|
link:src/main/resources/generate-composite-site-example.pom.xml[Example pom]

| ###### *GenerateRepositoryFacadeMojo*
|
generate-repository-facade
|
Generates a JBoss-friendly facade and files for a p2 repo - used for JBoss Tools Core, Central, EA, Core Tests, and Devstudio
|
link:src/main/resources/generate-repository-facade-example.pom.xml[Example pom]

| ###### *CreateFullSiteMojo*
|
create-full-site
|
DEPRECATED @since JBT 4.5.1.AM2. Creates an update site including index.html. Use generate-repository-facade instead.
|
link:https://github.com/jbosstools/jbosstools-build-sites/blob/master/aggregate/pom.xml#L59[Example pom]

| ###### *FetchSourcesFromManifests*
|

fetch-sources-from-manifests
|
DEPRECATED. For a list of projects and plugins, find the SHAs of those plugins' sources and fetch zips of those sources from github. No longer used since JBoss Tools uses jgit timestamps
|
link:src/main/resources/fetch-sources-from-manifests-example.pom.xml[Example pom]

| ###### *FetchZipsFromRepo*
|

fetch-zips-for-aggregate
|
DEPRECATED. Way to find sources for a given JBoss Tools build
|

| ###### *GenerateDirectoryXmlMojo*
|

generate-discovery-site
|
Create directory.xml file for use with a Mylyn Discovery site such as Red Hat Central.

Unused?
|

| ###### *BuildPublisherMojo*
|

publish-build
|
Unused?
|

|===
